sudo: required
install: true
services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DEPS_REPO=bluestreak/deps
    - MAGENTO_REPO=bluestreak/magento

before_script:
  - docker pull $DEPS_REPO:latest
  - docker pull $MAGENTO_REPO:latest

script:
  - >
    docker build
    -f deps.Dockerfile
    -t $DEPS_REPO:$COMMIT
    --cache-from $DEPS_REPO:latest
    .
  - >
    docker build
    -f Dockerfile
    -t $MAGENTO_REPO:$COMMIT
    --cache-from $MAGENTO_REPO:latest
    .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # Deps repo
  - docker tag $DEPS_REPO:$COMMIT $DEPS_REPO:$TAG
  - docker tag $DEPS_REPO:$COMMIT $DEPS_REPO:travis-$TRAVIS_BUILD_NUMBER

  # Magento repo
  - docker tag $MAGENTO_REPO:$COMMIT $MAGENTO_REPO:$TAG
  - docker tag $MAGENTO_REPO:$COMMIT $MAGENTO_REPO:travis-$TRAVIS_BUILD_NUMBER


  - docker push $DEPS_REPO
  - docker push $MAGENTO_REPO
